apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80 # porta interna del cluster
      targetPort: 80 # porta del container
  type: NodePort # Minikube usa NodePort per accedere dal browser host
