server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files $uri /index.html;
    }
}

# Servizio per le metriche applicative di nginx!
server {
    listen 8080;
    server_name localhost;

    location /stub_status {
        stub_status on;
        access_log off;
        allow 127.0.0.1; # Permette l'accesso solo al sidecar locale
        deny all;
    }
}